name: environment_win
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py37hcc03f2d_2
  - async_generator=1.10=pyhd8ed1ab_1
  - attrs=20.2.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py37hcc03f2d_1004
  - ca-certificates=2025.11.4=haa95532_0
  - certifi=2022.12.7=py37haa95532_0
  - cffi=1.14.3=py37hd6b71e5_1
  - chardet=3.0.4=py37hf50a25e_1008
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=3.1.1=py37hd6b71e5_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - idna=2.10=pyh9f0ad1d_0
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=h57928b3_254
  - ipykernel=5.5.5=py37h7813e69_0
  - ipython=6.5.0=py37_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - jedi=0.17.2=py37h03978a9_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py37h03978a9_2
  - jupyterlab=2.2.8=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - libblas=3.9.0=26_win64_mkl
  - libcblas=3.9.0=26_win64_mkl
  - libffi=3.3=h0e60522_2
  - liblapack=3.9.0=26_win64_mkl
  - libllvm10=10.0.1=hde8ddfe_3
  - libsodium=1.0.18=h8d14728_1
  - libzlib=1.2.11=h8ffe710_1014
  - llvmlite=0.34.0=py37h8b575af_2
  - mistune=0.8.4=pyh1a96a4e_1006
  - mkl=2020.2=h57928b3_256
  - mkl-service=2.3.0=py37h4ab8f01_2
  - mkl_fft=1.2.0=py37h3a3b6f7_1
  - mkl_random=1.1.1=py37h3bbf574_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37h03978a9_3
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.1=py_0
  - notebook=6.1.4=py37hc8dfbb8_1
  - numba=0.51.2=py37h414f9d2_0
  - openssl=1.1.1w=h2bbff1b_0
  - pandoc=2.11.0.2=hf4a77e7_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt_toolkit=1.0.15=py_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyrsistent=0.17.3=py37hcc03f2d_3
  - pysocks=1.7.1=py37h03978a9_5
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pywin32=303=py37hcc03f2d_0
  - pywinpty=2.0.8=py37h7f67f24_0
  - pyzmq=22.0.3=py37h0d95fc2_0
  - requests=2.24.0=pyh9f0ad1d_0
  - send2trash=1.5.0=py_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - simplegeneric=0.8.1=py_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.33.0=he774522_1
  - tbb=2020.3=h74a9793_0
  - terminado=0.9.1=py37h03978a9_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=h8ffe710_1
  - tornado=6.2=py37hcc03f2d_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=1.25.11=py_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - wheel=0.35.1=pyh9f0ad1d_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.3=h0e60522_3
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h8ffe710_1014
  - pip:
      - absl-py==2.1.0
      - alabaster==0.7.13
      - babel==2.14.0
      - cachetools==5.5.2
      - click==8.1.8
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cycler==0.11.0
      - deepdiff==6.7.1
      - docutils==0.19
      - et-xmlfile==1.1.0
      - exceptiongroup==1.3.1
      - execnet==2.0.2
      - fiona==1.9.6
      - fonttools==4.38.0
      - geopandas==0.10.2
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.3
      - igraph==0.10.8
      - imagesize==1.4.1
      - importlib-metadata==6.7.0
      - iniconfig==2.0.0
      - jinja2==3.1.6
      - kiwisolver==1.4.5
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matpowercaseframes==1.1.5
      - networkx==2.6.3
      - numpy==1.21.6
      - numpydoc==1.5.0
      - oauthlib==3.2.2
      - openpyxl==3.1.3
      - ordered-set==4.1.0
      - ortools==9.5.2237
      - packaging==24.0
      - pandapower==2.11.1
      - pandas==1.3.5
      - pillow==9.5.0
      - plotly==5.18.0
      - pluggy==1.2.0
      - protobuf==3.20.3
      - psycopg2==2.9.9
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyproj==3.2.1
      - pytest==7.4.4
      - pytest-xdist==3.5.0
      - python-igraph==0.10.8
      - pytz==2025.2
      - pyyaml==6.0.1
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scipy==1.7.3
      - shapely==2.0.7
      - snowballstemmer==3.0.1
      - sphinx==5.3.0
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - tenacity==8.2.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - texttable==1.7.0
      - tomli==2.0.1
      - torch==1.12.1+cu113
      - torchaudio==0.12.1+cu113
      - torchvision==0.13.1+cu113
      - tqdm==4.67.1
      - typing-extensions==4.7.1
      - werkzeug==2.2.3
      - xlsxwriter==3.2.2
prefix: C:\Users\Songy\.conda\envs\environment_win
